Added jwt token and removed token for authentication to the metadata …
Amsterdam/iiif-auth-proxy pull request #59
Opened 2021-01-19 19:37 UTC by kramer65

…server

2021-01-21 11:05 UTC, jklardie requested changes

2021-01-21 11:05 UTC, jklardie commented on src/iiif/views.py
> +            jwt_token = jwt.decode(request.GET.get('auth'), settings.SECRET_KEY, algorithms=["HS256"])
Algorithm moet naar settings

2021-01-21 11:05 UTC, jklardie commented on src/iiif/views.py
> +    # Check the jwt token if necessary
Je gaat nu zelf json web tokens checken, ik twijfel of dat wenselijk is. Mijn eerste gevoel zegt dat het beter is daar bestaande oplossingen voor te gebruiken.

2021-01-21 11:05 UTC, jklardie commented on src/iiif/views.py
> +    if not scope == settings.BOUWDOSSIER_EXTENDED_SCOPE and not (is_public and scope == settings.BOUWDOSSIER_READ_SCOPE):
`if not scope ==`  -> `if scope !=`

2021-01-21 11:05 UTC, jklardie commented on tests/test_iiif.py
> +        with time_machine.travel(datetime.now() - timedelta(days=2)):
nice!

2021-01-25 08:10 UTC, jklardie requested changes
Paar kleine changes

2021-01-25 08:10 UTC, jklardie commented on src/iiif/views.py
> +        return response
Niet heel erg fan van deze setup, zoals eerder besproken heeft mijn voorkeur een exception zoals tastypie doet: https://github.com/django-tastypie/django-tastypie/blob/master/tastypie/exceptions.py#L103

Je code ziet er dan iets leesbaarder uit:
```
try:
    ..hele
    ..reeks
    ..methods
    ..foo
    ..bar
except ImmediateHttpResponse as e:
    return e.response
```

2021-01-26 14:10 UTC, kramer65 commented on src/iiif/tools.py
> +def get_authentication_jwt(expiry_hours=24, key=settings.SECRET_KEY):
In principe is dit een voorbeeld wat ik doorstuur naar het dataportaal team. Dus deze wordt sowieso niet anders dan voor testen gebruikt in deze repo.

2021-01-26 14:13 UTC, kramer65 commented on src/iiif/tools.py
> +    if meta_response:
Klopt, maar omdat er dan een `return None, HttpResponse(...` zou staan vind ik het in dat geval niet duidelijk waarom die None gereturnd zou worden. In de naam van de leesbaarheid laat ik het dus zo.

2021-01-26 14:51 UTC, kramer65 commented on src/iiif/views.py
> +        return response
Idd netter. Done.

2021-01-26 14:58 UTC, jklardie approved these changes

2021-02-02 14:33 UTC, bheupers approved these changes

2021-02-04 09:46 UTC, merged